<a href="https://colab.research.google.com/github/AnupJoseph/numpex/blob/master/numpyex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
#swap columns of a matrix in numpy
arr = np.arange(9).reshape(3,3)
arr[:,0],arr[:,1] = arr[:,1],arr[:,0].copy()
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [0]:
#swap rows of a matrix in numpy
arr[0,:],arr[1,:] = arr[1,:],arr[0,:].copy()
arr

array([[4, 3, 5],
       [1, 0, 2],
       [7, 6, 8]])

In [0]:
#reverse rows of a numpy array
arr[:,::-1]

array([[5, 3, 4],
       [2, 0, 1],
       [8, 6, 7]])

In [0]:
#Generating random numbers between x and y
x,y = 5,10
rand_arr = np.random.uniform(x,y,size=(5,3))
rand_arr

array([[6.85381079, 8.4483336 , 8.60236764],
       [9.87003186, 5.71762519, 6.16482545],
       [7.03086433, 8.11687306, 9.44695486],
       [8.12496474, 7.96126992, 5.31838171],
       [5.6561182 , 5.04043681, 7.84322687]])

In [3]:
#Print only n decimal places using numpy
rand_arr = np.random.random((5,3))
n = 3
np.set_printoptions(precision=n)
rand_arr

array([[0.042, 0.504, 0.011],
       [0.697, 0.402, 0.757],
       [0.939, 0.589, 0.337],
       [0.689, 0.862, 0.661],
       [0.705, 0.52 , 0.148]])

In [6]:
#Supress scientific notation 
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True,precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [10]:
#keep string data intact while loading files

url = "/content/iris.data"
np.genfromtxt(url,delimiter=',',dtype=str)

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1